### PR TITLE
feat: component testing alpha

### PR DESCRIPTION
**Pull request by bahmutov**
Requires change to the test runner https://github.com/cypress-io/cypress/pull/5923
Adopts approach from https://github.com/bahmutov/cypress-react-unit-test/pull/108

- solves #43 XHR in Chrome problem 
- solves #94 (style injection)
- solves #194 (local style injection from test)
```js
import Todo from './Todo.vue'
import {mount} from 'cypress-vue-unit-test'

// let's make sure we can show the checked Todo item using CSS
const style = `
  .todo.done {
    text-decoration: line-through;
    color: gray;
  }
`
it('passes props via options object', () => {
  // if you want to pass props right away, without creating a template
  // use "propsData" key
  const options = {
    propsData: {
      title: 'finish test',
      done: true
    },
    style
  }
  mount(Todo, options)
  cy.get('.todo').should('have.class', 'done')
    // and the style was correctly applied
    .should('have.css', 'text-decoration-line', 'line-through')
})
```

- solves #122 (`document.body` points at the right iframe)
```js
import {mount} from 'cypress-vue-unit-test'

/* eslint-env mocha */
describe('document.body', () => {
  // https://github.com/bahmutov/cypress-vue-unit-test/issues/122
  it('is set correctly', () => {
    mount({
      mounted () {
        console.log('mounted!')
        console.log('document.body', document.body)
        document.body.innerText = 'Mounted!'
      }
    })
    cy.contains('Mounted!').should('be.visible')
  })
})
```
- [x] requires all specs to be changed and tested to make sure there is no breaking functionality

### CODE REVIEW

**Comment by bahmutov** [comment]
even the router tests are working
Screen Shot 2020-01-15 at 4 45 54 PM

**Comment by bahmutov** [comment]
You can inject external stylesheets, like this Tailwindcss card example
```js
it('renders card', () => {
  cy.viewport(1000, 500)
  mount({
    template: html
  }, {
    stylesheets: '/node_modules/tailwindcss/dist/tailwind.min.css'
  })
  cy.contains('.text-xl', 'Can coffee make you a better developer?')
})
```
Screen Shot 2020-01-15 at 11 37 07 PM

**Comment by probil** [comment]
Any updates on this? 
I need a fix for #122. Maybe be it can be extracted and merged in separated MR

**Comment by bahmutov** [comment]
still blocked by https://github.com/cypress-io/cypress/pull/5923

**Pull request merged**
