### PR TITLE
Fix Vuex integration and add Counter example tests

### PR DESCRIPTION
**Pull request by amirrustam**
Current fix for bahmutov/cypress-vue-unit-test#6

### CODE REVIEW

**Comment by bahmutov** [comment]
Wow I cannot check now but it is ... working???

**Comment by amirrustam** [comment]
@bahmutov I've made some great progress on this. The Vuex store not being reactive had to do with how Vuex manages its internal state. 

When creating a store with `Vuex.Store({ ... })`, a Vue instance (`_vm`) is initialized within the Store instance to make its internal state reactive:

```js
// vuex/src/store.js
store._vm = new Vue({
    data: {
      $$state: state
    },
    computed
  })
```

We create our Store instance with a different Vue "bundle" than the one we include with a `script` tag within the component iframe. This essentially makes that inner Vue instance go stale. 

The inner state will still change after button clicks that trigger mutations, but the watchers that look for state changes to add DOM manipulations to Vue's queueing system no longer work in this scenario.

So we need to use the global Vue within the component iframe to initialize the Store's inner Vue instance. When we run `mountVue`, we check for a `store` within the provided component, if it has one, then we reset this store's `_vm` with the `Vue` on the iframe `window`. This fixes the reactivity problem.

I've added tests for all the buttons within the `Counter` component:

vuex counter unit test

There is still one last lingering issue. The computed mapped getters on a component still go stale. So in templates instead of using `{{ evenOrOdd }}`, I have to do `{{ $store.state.eventOrOdd }}`. Obviously this is not idea, and I'm working on fixing this. This was just my first stab at the issue, and I have a couple of hunches!

I want Vue.js users to have a great experience with Cypress, and to use Cypress for all their tests. So I want to improve component unit-testing for them as much as possible.

**Comment by bahmutov** [comment]
I will merge this in - I was thinking about the global flag ... is this related to the two iframes? Maybe we can reflect the property from app iframe back into spec iframe to solve this.

**Comment by bahmutov** [comment]
I merged this because I think this improves the total experience, thanks a log for great work @amirrustam

**Comment by amirrustam** [comment]
@bahmutov we think the same. I did something similar earlier today, and it got everything fully working. I was going to commit and push it when I get home. Await my next pull request :)

**Pull request merged**
